### ISSUE TITLE
Cannot launch disco VM as launch timed out

### ISSUE THREAD

**Issue by powersj** [CanonicalLtd/multipass#735] opened 2019-04-19 16:35 UTC
```
$ multipass -vvv launch disco --name d1                                   
Configuring d1 /[2019-04-19T09:27:26.353] [warning] [qemu-img] Failed to open module: /snap/core/current/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/x86_64-linux-gnu/qemu/block-iscsi.so)


[2019-04-19T09:27:26.354] [warning] [qemu-img] Failed to open module: /usr/lib/x86_64-linux-gnu/qemu/block-curl.so: undefined symbol: qemu_mutex_lock_func


[2019-04-19T09:27:26.357] [warning] [qemu-img] Failed to open module: /usr/lib/x86_64-linux-gnu/qemu/block-rbd.so: undefined symbol: RbdAuthMode_lookup


/[2019-04-19T09:27:26.763] [debug] [d1] process working dir '/snap/multipass/716/qemu'

[2019-04-19T09:27:26.763] [info] [d1] process program 'qemu-system-x86_64'

[2019-04-19T09:27:26.763] [info] [d1] process arguments '--enable-kvm, -hda, /var/snap/multipass/common/data/multipassd/vault/instances/d1/ubuntu-19.04-server-cloudimg-amd64.img, -drive, file=/var/snap/multipass/common/data/multipassd/vault/instances/d1/cloud-init-config.iso,if=virtio,format=raw,snapshot=off,read-only, -smp, 1, -m, 1024M, -device, virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:0b:11:8f, -netdev, tap,id=hostnet0,ifname=tap-484b336f831,script=no,downscript=no, -qmp, stdio, -cpu, host, -chardev, null,id=char0, -serial, chardev:char0, -nographic'

Starting d1 /[2019-04-19T09:27:26.805] [info] [d1] process state changed to Starting

[2019-04-19T09:27:26.806] [info] [d1] process state changed to Running

[2019-04-19T09:27:26.806] [info] [d1] process started

launch failed: timed out waiting for instance to respond  

$ multipass info d1
Name:           d1
State:          UNKNOWN
IPv4:           --
Release:        --
Image hash:     3c6abd31d492 (Ubuntu 19.04)
Load:           --
Disk usage:     --
Memory usage:   --

$ snap info multipass
name:      multipass
summary:   Ubuntu at your fingertips
publisher: Canonical✓
license:   unset
description: |
  Multipass gives you Ubuntu VMs in seconds. Just run `multipass launch` and
  it'll do all the setup for you. Check out `multipass find` for a list of
  available images. More details you can find under `multipass help`.
commands:
  - multipass
  - multipass.virsh
services:
  multipass.libvirt-bin: simple, enabled, inactive
  multipass.multipassd:  simple, enabled, active
snap-id:      mA11087v6dR3IEcQLgICQVjuvhUUBUKM
tracking:     beta
refresh-date: 17 days ago, at 12:01 PDT
channels:
  stable:           –                                             
  candidate:        –                                             
  beta:             0.6.0                  2019-04-02 (716) 113MB classic
  edge:             0.7.0-dev.115+g8295962 2019-04-19 (740) 113MB classic
  core16/stable:    –                                             
  core16/candidate: –                                             
  core16/beta:      0.6.0                  2019-04-02 (716) 113MB classic
  core16/edge:      0.7.0-dev.236+gcd11605 2019-03-29 (712) 113MB classic
installed:          0.6.0                             (716) 113MB classic

```

**Comment by Saviq** [comment] 2019-04-19 16:40
Hey, this just got fixed in edge: #690 

Duplicate of #690

**Closed by Saviq** 2019-04-19 16:40 UTC
