### ISSUE TITLE
[cosmetic issue/enhancement] multipass shell: handling text color

### ISSUE THREAD

**Issue by daviehh** [CanonicalLtd/multipass#1026] opened 2019-09-05 21:48 UTC
multipass v0.8.0, on macos. `multipass shell` may have issues when displaying colored text, while directly connecting to the vm through ssh works fine. e.g. screenshot below for `htop`
through `multipass shell`:
<img width="1153" alt="Screen Shot 2019-09-05 at 5 42 57 PM" src="https://user-images.githubusercontent.com/25255906/64385648-faf02700-d004-11e9-85ca-5b7214abef81.png">
directly via ssh:
<img width="1153" alt="Screen Shot 2019-09-05 at 5 43 00 PM" src="https://user-images.githubusercontent.com/25255906/64385657-fdeb1780-d004-11e9-8d96-2a30c6ab09ff.png">

**Comment by Saviq** [comment] 2019-09-06 06:58
This is probably related to (or even duplicate of) #1004.

**Comment by daviehh** [comment] 2019-09-06 18:23
Yup, confirmed with `export TERM=xterm-256color` the display inside `multipass shell` work as expected. Thanks! Until https://github.com/CanonicalLtd/multipass/issues/1004, one may set the export in .bashrc, etc.

**Comment by Saviq** [comment] 2019-09-07 17:03
Ack, I'll mark this as duplicate of #1004, then :)

**Comment by Saviq** [comment] 2019-09-07 17:03
Duplicate of #1004.

**Closed by Saviq** 2019-09-07 17:03 UTC
Labels: bug, good first issue, help wanted
