### ISSUE TITLE
multipassd dies when cloud-images.ubuntu.com is not accessible

### ISSUE THREAD

**Issue by morphis** [CanonicalLtd/multipass#673] opened 2019-03-11 08:02 UTC
Saw in my system logs today that multipassd failed to startup yesterday because my laptop was without Wifi and cloud-images.ubuntu.com was not accessible:

```
Mär 10 18:51:30 earth multipassd[13215]: Host cloud-images.ubuntu.com not found
Mär 10 18:51:30 earth systemd[1]: snap.multipass.multipassd.service: Main process exited, code=exited, status=1/FAILURE
Mär 10 18:51:30 earth systemd[1]: snap.multipass.multipassd.service: Failed with result 'exit-code'.
Mär 10 18:51:30 earth systemd[1]: snap.multipass.multipassd.service: Service hold-off time over, scheduling restart.
Mär 10 18:51:30 earth systemd[1]: snap.multipass.multipassd.service: Scheduled restart job, restart counter is at 5.
Mär 10 18:51:30 earth systemd[1]: Stopped Service for snap application multipass.multipassd.
Mär 10 18:51:30 earth systemd[1]: snap.multipass.multipassd.service: Start request repeated too quickly.
Mär 10 18:51:30 earth systemd[1]: snap.multipass.multipassd.service: Failed with result 'exit-code'.
Mär 10 18:51:30 earth systemd[1]: Failed to start Service for snap application multipass.multipassd.
```

This is with multipass v0.5 (revision 587)

**Comment by Saviq** [comment] 2019-03-11 08:19
Hey, this is fixed in `master` via #611.

Duplicate of #555

**Closed by Saviq** 2019-03-11 08:19 UTC
