### ISSUE TITLE
Can an instance be duplicated or extended ?

### ISSUE THREAD

**Issue by Pigmalion** [CanonicalLtd/multipass#726] opened 2019-04-17 13:39 UTC
Hi, I am running VM with multipass and the set up of each instance is a bit complicated since I am raising a cluster with microk8s for dev environment.
 How can I simply clone an instance and the modify it as i need?
Tnhanks!

**Comment by Saviq** [comment] 2019-04-17 13:50
Hi @Pigmalion it's currently not possible to clone instances (see #208). We're pondering on how to do it well, since the instances would need new hostnames, network addresses and such.

In the mean time, is it complicated as well as time consuming? Maybe `--cloud-init` would help to automate the steps?

**Comment by Saviq** [comment] 2019-04-17 13:51
I'm going to close this as duplicate.

Duplicate of #208.

**Closed** 2019-04-17 13:51 UTC
Labels: duplicate
