### ISSUE TITLE
Strange error when copying into invalid destination

### ISSUE THREAD

**Issue by sergiusens** [CanonicalLtd/multipass#881] opened 2019-07-03 00:50 UTC
If I do

    multipass copy-files /tmp/tmpv_9dce2_/core.snap snapcraft-my-snap-name:/tmp/snaps/core.snap

I get this in response:

    transfer failed: [scp push] failed: 'scp status code 1d not valid'

I have figured out that this is due to not having the right permissions at the destination (after a while), it would be nice to get a cleaner error message for this scenario.

**Comment by townsend2010** [comment] 2019-08-01 16:10
This is a duplicate of #698.  I'd like to switch over `transfer` of files to the much more robust sftp protocol soon.

**Closed by townsend2010** 2019-08-01 16:10 UTC
Labels: bug
