### ISSUE TITLE
feature request: guest exec via serial port

### ISSUE THREAD

**Issue by dshcherb** [CanonicalLtd/multipass#372] opened 2018-09-10 09:28 UTC
It would be good to have an ability to manage a guest VM via a virtio serial port instead of relying on ssh.

https://qemu.weilnetz.de/doc/qemu-ga-ref.html#index-guest_002dexec
https://wiki.libvirt.org/page/Qemu_guest_agent
"Command: guest-exec
Execute a command in the guest
...
capture-output: boolean (optional)
bool flag to enable capture of stdout/stderr of running process. defaults to false."

https://www.linux-kvm.org/page/Virtio-serial_API

`multipass exec bash` would be one of the most frequent use-cases.

**Comment by Saviq** [comment] 2018-09-10 10:05
That would require logging in (with a password) on the serial console and executing the command, if we're only talking debugging purposes, I think we'd rather give access to the console itself.

Is there another use case you're thinking of?

**Comment by dshcherb** [comment] 2018-09-10 10:46
@Saviq 

I think there are two use-cases: debugging and running some automation that can potentially disrupt the network connectivity via a serial port, wait something on stdin or provide stdout.

I don't think you need to log in necessarily if we are talking about the QEMU Guest Agent (GA) exec.

Just using a serial port would require logging in. The guest kernel and grub would need to be configured to use the right console as well.

https://www.kernel.org/doc/html/latest/admin-guide/devices.html#virtual-consoles-and-the-console-device
> /dev/console, is the device to which system messages should be sent, and on **which logins should be permitted in single-user mode**
https://www.kernel.org/doc/html/latest/admin-guide/serial-console.html
> You can specify multiple console= options on the kernel command line. Output will appear on all of them. The **last device will be used when you open /dev/console**

https://www.gnu.org/software/grub/manual/grub/grub.html (GRUB_TERMINAL_INPUT, GRUB_TERMINAL_OUTPUT or GRUB_TERMINAL)

As an example, OpenVZ 7 (QEMU-based) uses QEMU GA multiple virtio serial ports for multiplexed I/O:
https://lists.openvz.org/pipermail/users/2016-February/006791.html

So the use-case for multipass would be something like:

cat file | multipass exec <name> <some-binary-that-needs-stdin>
multipass exec <name> <some-binary-that-outputs-something> | grep pattern

Here are some notes on testing: https://fedoraproject.org/wiki/Features/VirtioSerial#Testing_console_IOx

virtio serial ports are also used for Spice remote desktop.

**Comment by Saviq** [comment] 2018-09-10 10:54
> cat file | multipass exec
> multipass exec | grep pattern

FWIW these should work already. If it doesn't, it's a bug we need to fix.

The network story is a bit different, indeed if this is something we'd want to support some kind of non-networked situation would have to happen. Not sure if we'd use the guest agent though (it is qemu specific after all).

**Comment by dshcherb** [comment] 2018-09-10 11:17
@Saviq 

> FWIW these should work already. If it doesn't, it's a bug we need to fix.

➜  ~ multipass exec proxytest echo 1
1
➜  ~ echo 1 | multipass exec proxytest cat   
1

When network connectivity is there they do work.

> Not sure if we'd use the guest agent though

I think it will be specific to the hypervisor support for serial ports. Not sure which hypervisors are used for other operating systems right now.

QEMU might well work on Windows and mac os X:
https://www.qemu.org/2017/11/22/haxm-usage-windows/
https://github.com/intel/haxm#intel-hardware-accelerated-execution-manager-haxm

**Comment by Saviq** [comment] 2019-02-21 13:47
Duplicate of #136.

**Closed by Saviq** 2019-02-21 13:47 UTC
Labels: enhancement, question
