### ISSUE TITLE
multipassd segfaulted and died

### ISSUE THREAD

**Issue by ColinIanKing** [CanonicalLtd/multipass#668] opened 2019-03-06 20:01 UTC
Got a segfault from multipassd:

[12428.673583] multipassd[3072]: segfault at 59f1990 ip 00007f52eb1e184e sp 00007ffcfdf0c4a8 error 4 in libc-2.23.so[7f52eb142000+1c0000]
[12428.673595] Code: 8d 0c 12 48 29 f8 48 29 d0 48 39 c8 0f 82 07 01 00 00 48 83 fa 10 0f 86 8b 01 00 00 f3 44 0f 6f 06 48 83 fa 20 f3 44 0f 7f 07 <f3> 44 0f 6f 44 16 f0 f3 44 0f 7f 44 17 f0 77 12 48 89 f8 c3 0f 1f

**Comment by Saviq** [comment] 2019-03-06 21:33
Any idea when this happened? Were you maybe deleting instances around then? If that's so, `--edge` should have that fixed.

**Comment by ColinIanKing** [comment] 2019-03-06 23:08
This did occur when I was deleting a bunch of instances; I'll try --edge. thanks!

**Comment by Saviq** [comment] 2019-03-07 08:07
Duplicate of #585

**Closed by Saviq** 2019-03-07 08:07 UTC
Labels: question
