### ISSUE TITLE
Mount fails periodically with `transport endpoint is not connected`

### ISSUE THREAD

**Issue by tasdomas** [CanonicalLtd/multipass#689] opened 2019-03-19 16:07 UTC
Running a multipass VM (ubuntu 16.04) with two mounted directories. Periodically the mount fails with the error: "cannot open directory '.': Transport endpoint is not connected"

This usually happens when running something intensive (like snapcraft) in the vm.

**Comment by Saviq** [comment] 2019-03-19 16:17
Hi @tasdomas this is fixed in edge (through #582) - we'll be releasing a new version soon.

**Comment by Saviq** [comment] 2019-03-19 16:17
Duplicate of #652.

**Closed by Saviq** 2019-03-19 16:17 UTC

**Comment by tasdomas** [comment] 2019-03-19 16:22
Thanks!

**Comment by awesome-manuel** [comment] 2020-01-03 13:11
@Saviq Still happens for me during `snapcraft prime` especially when the host directory is inside an encfs encrypted home.

**Comment by Saviq** [comment] 2020-01-07 17:29
Hi @awesome-manuel this suggests it's a slightly different problem, can you please file a new issue with any details you can think of?
