### ISSUE TITLE
Instances has no IPv4 address

### ISSUE THREAD

**Issue by trankchung** [CanonicalLtd/multipass#839] opened 2019-06-13 14:17 UTC
I launched an instance and it's not having an IP address. I've checked all the commands as well as the launch command's help but there's no option to specify an IP. Could you please assist?

```
C:\>multipass list
Name                    State             IPv4             Image
bionic                  Running           N/A              Ubuntu 18.04 LTS

C:\>multipass info bionic
Name:           bionic
State:          Running
IPv4:           N/A
Release:        Ubuntu 18.04.2 LTS
Image hash:     d29ee3dcb777 (Ubuntu 18.04 LTS)
Load:           0.00 0.05 0.04
Disk usage:     996.7M out of 48.3G
Memory usage:   72.6M out of 985.4M
```

**Comment by Saviq** [comment] 2019-06-13 14:38
Hi @trankchung that's a current limitation of the VirtualBox backend, or rather VBox's itself.

With the default networking the virtual machine does not get an IP visible from the host. It's only possible when bridging to an existing network, which is on our roadmap (#118).

Can you confirm for me that `multipass shell bionic` does work?

**Comment by trankchung** [comment] 2019-06-13 14:41
Yes. The `multipass shell bionic` does work. I'll wait for that enhancement then. Thanks.

**Comment by Saviq** [comment] 2019-06-13 14:50
Duplicate of #118.

**Closed by Saviq** 2019-06-13 14:50 UTC
Labels: question
