### ISSUE TITLE
VM is not able to reach bridge 192.168.64.1

### ISSUE THREAD

**Issue by zhiminwen** [CanonicalLtd/multipass#1080] opened 2019-09-20 17:23 UTC
I am running the multipass on Mac. 

When the VM is up. I can launch the shell to go inside the VM. However the ping command 
`ping 192.168.64.1` just hang.

I can ping from host to the VM's ip 192.168.64.5

on the host, there is a bridge100 device active with one nic card attached. if I down this nic card then the VM is not pingable. Looks like things are correct.

Any clue to further check?

**Comment by townsend2010** [comment] 2019-09-24 12:57
Hi @zhiminwen,

Is everything else working correctly inside the Multipass VM instance, like can it connect to the Internet and get updates, etc?  I'm not sure why you really need to ping the bridge if everything is working correctly.

**Comment by Saviq** [comment] 2019-09-30 11:20
Hi @zhiminwen I'm going to close this for now. It's more than likely that the bridge setup (done by `bootp`) is preventing you from pinging it, by design.

**Closed by Saviq** 2019-09-30 11:20 UTC
Labels: question
